# Generated by Django 3.0.5 on 2023-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrading',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
