# Generated by Django 3.0.5 on 2023-07-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230707_1019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stocktrading',
            table='stock_trading',
        ),
    ]
