# Generated by Django 4.2.3 on 2023-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_auto_20230711_0453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companylist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocktrading",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocktrading",
            unique_together={("company", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="userprofile",
            unique_together={("company_name", "buying_date")},
        ),
    ]
