# Generated by Django 4.2.3 on 2023-07-17 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_companylist_id_alter_stocktrading_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyList",
        ),
    ]
